language: node_js
sudo: false

node_js:
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "node"

before_script:
  # install node.js dependencies, travis runs `npm install` by default
  - npm install -g gulp

script:
  npm build